[update]
channel = "stable"
version_check = true
manifest_check = true

[worktrees]
directory = "~/datahub/repos/worktrees/"

[ui.toast]
delivery = "system"
delay_seconds = 5


[ui]
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true

[experimental]
switch_ascii_input_source_in_prefix = true

[theme]
name = "catppuccin"
auto_switch = true
