[tools]
fd = "latest"
fzf = "latest"
neovim = "latest"
usage = "latest"
starship = "latest"
docker-cli = "latest"
docker-compose = "latest"
uv = "latest"
awscli = { version = "latest", symlink_bins = "true" }
gcloud = "latest"
k9s = "latest"
kubectl = "latest"
aws-sso = "latest"
claude-code = { version = "latest", bin = "claude", platforms = """
[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
github-cli = "latest"
1password-cli = "latest"

[env]
DOCKER_DEFAULT_PLATFORM='linux/arm64'


