[tools]
fd = "latest"
fzf = "latest"
neovim = "latest"
usage = "latest"
starship = "latest"
docker-cli = "latest"
docker-compose = "latest"
uv = "latest"

[env]
DOCKER_DEFAULT_PLATFORM='linux/arm64'


